### ISSUE TITLE
Cannot open file with unicode characters in path

### ISSUE THREAD

**Issue by paiyuchen** [veusz/veusz#216]
In ver. 2.x, there will be an error if the file path contains unicode characters:

UnicodeDecodeError: 'mbcs' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

But it works fine in ver. 1.x.

**Comment by jeremysanders** [comment]
Sorry - I can't reproduce this and I haven't received any other error reports with this problem.

What operating system are you using? Can you give some example filenames which fail? When do they fail?

**Comment by jeremysanders** [comment]
Oh, and what language/region is your operating system set up for?

**Comment by paiyuchen** [comment]
You could try 許功蓋 as the file name to capture the problem.
It will fail upon startup.

The language of OS is Traditional Chinese.
Both my Windows 7 and 10 computers can see the same problem.

**Comment by jeremysanders** [comment]
It works for me with that filename on saving and loading.

Do you mean it fails if you double-click on the document to open veusz with the document?

**Comment by paiyuchen** [comment]
Yes.

Actually it also works for me with load.

**Comment by jeremysanders** [comment]
This looks tricky to fix. Veusz passes the arguments to Qt, then Qt removes its specific arguments, Veusz gets the arguments back from Qt and then Veusz interprets its arguments.

Unfortunately Qt mangles the arguments which it can't interpret. I'll have to think about a solution.

**Comment by paiyuchen** [comment]
Thanks. I'll use v1.27 for now and wait for the fix.

**Comment by jeremysanders** [comment]
It seemed to bit easier than I thought. The above patch fixes the problem for me on Windows. I've avoiding taking the arguments from Qt. It should be included in the next release. I plan to make a new release soon.

**Comment by jeremysanders** [comment]
Ok. I've released 2.1.1 which should fix this.

**Comment by paiyuchen** [comment]
The problem still exists in Chinese Windows. For English it is OK with unicode characters now.
Maybe I should post the entire error message to help you debug:

Traceback (most recent call last):
  File "veusz\utils\safe_eval.py", line 200, in compileChecked
  File "ast.py", line 35, in parse
UnicodeDecodeError: 'mbcs' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "veusz\document\loader.py", line 113, in executeScript
  File "veusz\utils\safe_eval.py", line 202, in compileChecked
ValueError: Unable to parse file: 'mbcs' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

**Comment by jeremysanders** [comment]
Ok - I'll look at this later when I get time

**Comment by jeremysanders** [comment]
Would it be possible to try out this version? Apparently it fixes the problem for Korean:
https://drive.google.com/open?id=197OlB8haJcImF1MblaSKVnL6cUSDc9DB

**Comment by paiyuchen** [comment]
This version solves the problem. Thanks!

**Comment by jeremysanders** [comment]
The fix will be in the next proper release
