### ISSUE TITLE
Feature Request: get rid of _bad_ restrictions to use python and numpy functions, make simler use of numpy.genfromtxt()

### ISSUE THREAD

**Issue by And0k** [veusz/veusz#260]
Now to load 2D data from format which requres _skip_header_ and _converters_ features of genfromtxt() I have to perform following operations:
`AddCustom(u'definition', u'f', u'lambda fun, *args: fun(*args)')`
`AddCustom(u'definition', u'fileDataSource', u"f(lambda fn: fn[:f(fn.rfind, '/')], f(FILENAME().replace, '\\\\', '')) + '/CSV/filename.CSV'")`
Desciption of what I done but should not to do:
1. Hack to can use unsafe functions: here it is a _replace_ and _rfind_.
2. Add current directory to hardcode only relative path;
    Replace '\\' which is added before some symbols by useful FILENAME() function.

Then I can use
`SetData2DExpression(u'col', u"genfromtxt(fileDataSource, skip_header=34, encoding='cp1250', converters= {0: fDate2num, 1: fTime2num}, delimiter= ',')", linked=True)`
where fDate2num,fTime2num is defined in Custom definitions

**Comment by And0k** [comment]
Proposed solution: make program more Python-friendly. For this more changes should be done!
Extend and combine "Data Create..." and "Custom Definitions" GUI to "Python Edit Window" - main tool for inserting and editing expressions, where possible to 
- input multirow code and functions,
- filter them by type/name, 
- sort by evaluation order,
- code all GUI functions (DatasetPlugins): I imagine that the code can be inserted by using existed menu
...

**Comment by jeremysanders** [comment]
Some good ideas there. The safety functionality is there because a bad veusz document can do anything to your computer.

Maybe it would be better to store checksums of known scripts when saving documents, and to check opened documents against them, rather than trying to check code. Alternatively, they could be signed. It will cause some problems if people modify documents with a text editor, however, as some sort of warning would be required.

Regarding extending the GUI, it might be possible to add more, though because the internals of Veusz change it would break peoples's, unless there is a special API.

**Comment by And0k** [comment]
Yes, I think that signing is a good idea. It also will gives info about who made veusz script. Warning will be required only if Veusz user _and_ opened file author are different _and_ some of **writing** python/numpy functions or **imports** are used _and_ not possible to use some of [this](https://wiki.python.org/moin/Asking%20for%20Help/How%20can%20I%20run%20an%20untrusted%20Python%20script%20safely%20%28i.e.%20Sandbox%29) methods (I think chroot jail is best). It will also be useful to disable warnings in GUI for some period. It will helps open files modified in text editor be opened by Veusz and saved with control code without any warnings. Alternatively call to special veusz function will be required to generate public checksum based on private key and checksum of file to write it in header (python comment) of veusz file.

But about vsz files! To screen all commands (even general python code, even all constants) to text is a big wall for interoperability. For example, after some veusz update my vsz-file only hangs when opening. Debugging was show some infinite looping but I do not understand why. I have experience of manually rewrite all in clean python with reordering expressions in dependence order. Then I used veusz to render only final results. I am indisposed to write this normal python expressions back to strings.

There is also other walls in Veusz:
- python console should access to all variables initially (Is it not main purpose of it to experiment with existed data? Why use GetData?)
- labels in graphics (why use special new(!) syntax (DATA)? - IMHO the use of python 3.6 fstrings will be best option). And should be possible to code array of strings
- all other GUI values have no access to variables at all :(

**Comment by And0k** [comment]
Depended request: allow default values in custom definitions of functions (lambdas)

**Comment by And0k** [comment]
Suggestion for initial problem (step to wanted progress):
1. allow custom functions before Veusz importing functions
2. allow Veusz importing functions use custom functions or its results
(I achieve this by modifying vsz file, but my commands lost after saving document in GUI)

**Comment by And0k** [comment]
Depended request: allow numpy.linalg functions in expressions? (already works in Veusz console)

**Comment by jeremysanders** [comment]
I'm planning on making some changes to the security model which should help Veusz-python interoperability. I've implemented in the "security_v2" branch (https://github.com/veusz/veusz/tree/security_v2) these things:

  * Documents are considered "trusted" if started from scratch, loaded from a trusted directory (or subdirectory), or the user clicks "Allow" when loading or "Trust" from the file menu.
  * Any trusted document can import from any Python module or a Python module name
  * There are no restrictions on the Python code in expressions, etc, for trusted documents
  * Users can add to the list of trusted directories in the preferences dialog (examples directory is automatically trusted)

For the future, I could look at adding a code editor for interactive Python function editing.

**Comment by And0k** [comment]
The only difference for documents from trusted locations in Veusz 3.3.1.1 is absence of starting dialog window about not secure code. Not safe code still not works:

- if  it is embedded in Veusz string arguments (Widget options, Custom Definitions) without `--unsafe-mode` command line option
- exporting _unsafe_ file with `--export=FILE` command line option
- when trying to load it in embedded mode

**Comment by And0k** [comment]
yes

**Comment by And0k** [comment]
In my preferences I added full disk "D:", but after confirmation of preferences dialog box the location is showed as **"D:/" and this not works**. But now I add descendant directories, they are listed without final slash ("/") and it seems that all works.

**Comment by And0k** [comment]
The problem is that directories in Preferences / Security cannot be entered at all in Windows, since the path is stored in them with the "/" sign, unlike if the directory is entered automatically (with "\") through the start dialog  when Veusz detects an unsafe code
